### PR TITLE
Issue #1965 - Fix label resolution for non-captured regex

### LINKED ISSUE #1965: Directive resolve_regexp returns invalid labels
### What version of gazelle are you using?
`master`

### What version of rules_go are you using?
`0.50.1`

### What version of Bazel are you using?
`7.4.0`

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
MacOS Arm64

### What did you do?

Declare a resolve_regexp directive.
`# gazelle:resolve_regexp py foo\. //x/y/z`

Create a Python file with the following import:
from foo.bar import baz

### What did you expect to see?
`deps` should resolve to `//x/y/z` when running Gazelle

### What did you see instead?
`deps` resolves to //x/y/zbar when running Gazelle

[This pull request](https://github.com/bazel-contrib/bazel-gazelle/pull/1822) introduces a change that attempts to create a label from the import statement using regex.  This is problematic, because if the regex does not match on the entire import statement, it will only replace pieces of the import statement, resulting in an incorrect label that still passes the `label.Parse()` check and is then written to the BUILD file.

For example, the import statement passed to `FindRuleWithOverride()` and then `o.resolveRegexDep()` in the above example is the string `foo.bar`.  

The following is then called inside of `resolveRegexDep()`:
`o.ImpRegex.ReplaceAllString("foo.bar", "//x/y/z")`

[According to the docs](https://cs.opensource.google/go/go/+/refs/tags/go1.23.2:src/regexp/regexp.go;l=572):
> // ReplaceAllString returns a copy of src, replacing matches of the [Regexp]
> // with the replacement string repl.
> // Inside repl, $ signs are interpreted as in [Regexp.Expand].

Thus, we end up with the label `//x/y/zbar`.

Other regex passed into the same directive has other corner cases that can be hit, and result in various invalid labels.

Creating the label by running `ReplaceAllString()` appears to contain many corner cases where regex that has been successfully utilized in the past now results in invalid labels.

### PR DESCRIPTION
**Pull request by alandonham**
**What type of PR is this?**
Bug fix

**What package or component does this PR mostly affect?**
resolve

**What does this PR do? Why is it needed?**
This change resolves an issue with regex_replace where the default behavior attempts to perform a string replacement using regex, but results in an invalid label.

**Which issues(s) does this PR fix?**
Fixes #1965

**Other notes for review**

### CODE REVIEW

File: resolve/config.go [hunk 1]
```diff
@@ -64,7 +64,12 @@ func (o regexpOverrideSpec) matches(imp ImportSpec, lang string) bool {
 }
 
 func (o regexpOverrideSpec) resolveRegexpDep(imp ImportSpec) label.Label {
-
+	// If NumSubexp() returns 0, then there are no captures in the regex,
```
Comment (fmeum) [inline resolve/config.go:67]: Now that I thought about this more, I realized that adding a capturing group without the intention of capturing it is probably somewhat common (`(a|b)` is simply less verbose than `(?:a|b)`). 

Maybe looking for back references in the replacement string is a better signal? What do you think?

Comment (alandonham) [reply resolve/config.go:67]: Sorry for the delay, last week was very busy for me.  I should get back around to looking at this a bit today.

File: resolve/config.go [hunk 2]
```diff
@@ -64,7 +64,12 @@ func (o regexpOverrideSpec) matches(imp ImportSpec, lang string) bool {
 }
 
 func (o regexpOverrideSpec) resolveRegexpDep(imp ImportSpec) label.Label {
-
+	// If "$" is found in the dependency string, then backreferences exist and
+	// ReplaceAllString() should be run on the string to substitute in the
+	// correct replacement strings to build the label.
+	if !strings.Contains(o.dep.String(), "$") {
+	    return o.dep
+	}
```
Comment (alandonham) [inline resolve/config.go:72]: This follows the [same logic](https://cs.opensource.google/go/go/+/refs/tags/go1.23.2:src/regexp/regexp.go;l=574) found in the `regex` Go stdlib to determine if backreferences exist.

I'm not entirely sure these are really backreferences, as the Go stdlib doesn't support backreferences, but it at least is indicating that the user expects regex to perform string replacement.  I think it is more accurately referred to as `Regexp.Expand` in this library.

File: resolve/config.go (hunk 1 above)
Comment (alandonham) [reply resolve/config.go]: I looked into it a bit more and I agree with your statement.  Backreferences, or `regex.Expand` usage via "$" is a better signal.

File: resolve/config.go (hunk 2 above)
Comment (fmeum) [reply resolve/config.go:72]: In theory `$` could be escaped, but since `$` is pretty unlikely to make it into a label, let alone into a replace pattern, I think that's okay for now.

**Review by fmeum — APPROVED** [review]

File: resolve/config.go (hunk 1 above)
Comment (fmeum) [reply resolve/config.go]: Thanks, don't worry, we're all busy :⁠-⁠)
